#! /bin/sh
bspc config border_width 2
bspc config window_gap 15
bspc config pointer_modifier mod4
bspc monitor -d 1 2 3 4 5

#bspc rule -a firefox desktop=^1 follow=off focus=on

bspc config normal_border_color "#4d4d4d"
bspc config active_border_color "#ffffff"
bspc config focused_border_color "#ffffff"
bspc config presel_feedback_color "#4d4d4d"

sxhkd &
nitrogen --restore &
picom & --experimental-backends
polybar main &
dunst &
