#! /bin/sh
bspc config border_width 0
bspc config window_gap 15
bspc config pointer_modifier mod4
bspc monitor -d 1 2 3 4 5

bspc rule -a osu! desktop=^3 follow=off focus=on
bspc rule -a steam desktop=^3 follow=off focus=on
bspc rule -a firefox desktop=^1 follow=off focus=on
bspc rule -a discord desktop=^2 follow=off focus=on
bspc rule -a lutris desktop=^3 follow=off focus=on

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

bspc config active_border_color "#6272a4"
bspc config focused_border_color "#8be9fd"

sxhkd &
nitrogen --restore &
picom & --experimental-backends
polybar main &
dunst &
