#! /bin/sh
bspc config border_width 0
bspc config window_gap 10
bspc config pointer_modifier mod4
bspc monitor -d 1 2 3 4 5

#bspc rule -a firefox desktop=^1 follow=off focus=on

bspc config normal_border_color "#4d4d4d"
bspc config active_border_color "#ffb200"
bspc config focused_border_color "#ffb200"
bspc config presel_feedback_color "#4d4d4d"

polybar main &

sxhkd &

nitrogen --restore &
            
picom &
            
setxkbmap es &
            
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
